# render.yaml - Configuración para Render
services:
  - type: web
    name: monitoring-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: "10000"
      - key: FIREBASE_CREDENTIALS
        sync: false  # Se configura manualmente en el dashboard de Render